### ISSUE TITLE
[BUG] Error before making a runway!

### ISSUE THREAD

**Issue by V2suOffical** [qbcore-framework/qb-lapraces#28]
I want to start racing and then it throws me an error like this:
@qb-lapraces/server/main.lua:238: attempt to index a nil value (field '?')

**Comment by Sometimeshappen** [comment]
I have the same problem, i just create one race for testing but this error happen

![96b565eb01d01667902afe0af2c1cb90](https://user-images.githubusercontent.com/113055577/188948560-90a53302-441d-451d-80a8-222a753a0b50.png)

**Comment by w4fflz** [comment]
I am not able to replicate this.  Please fill out the below template

**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Use this item '....' (item's name from shared.lua if applicable)
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**
Add any other context about the problem here.
